### ISSUE TITLE
Group dropdown not showing

### ISSUE THREAD

**Issue by blenezet** [jspreadsheet/ce#1359]
Hi,

I'm trying to set up "grouping" in a dropdown box (see column description below) but unfortunately, these groups are not showing (we can see a blank line with no text). It sounds like a CSS issue. Would you be able to tell me which CSS properties I should look at to attempt to resolve this? Alternatively, would you be able to give me some ropes on how to debug this?

Many thanks in advance

Kind regards
Bertrand
![grid_dropdown_with_group_not_showing](https://user-images.githubusercontent.com/64902620/115573767-56962380-a2c1-11eb-9b9b-f085889d9956.png)
{
    type: 'dropdown',
    id: 'type',
    submitType: 'array',
    title: t.type,
    width: '100',
    columnDrag: true,
    source: [
      { group:'Agriculture, Forestry and Other Land Use', id: 'afolu.01', name: 'Avoided Ecosystem Degradation' },
      { group:'Agriculture, Forestry and Other Land Use', id: 'afolu.02', name: 'Ecosystem Creation or Restoration' },
      { group:'Renewable Energy', id: 're.01', name: 'Biomass' },
      { group:'Renewable Energy', id: 're.02', name: 'Biogas' },
      { group:'Energy Efficiency and Fuel Switch', id: 'eefs.01', name: 'Energy Demand, Domestic' },
      { group:'Energy Efficiency and Fuel Switch', id: 'eefs.02', name: 'Energy Demand, Industrial'}
    ]
  }

**Comment by GBonnaire** [comment]
Hi,

It is this CSS for group name :
```CSS
.jdropdown-picker .jdropdown-group-name
{
    font-size: 1em;
    text-transform: uppercase;
    padding-top:10px;
    padding-bottom:10px;
    display: block;
    border-bottom: 1px solid #e6e6e8;
    padding-left:20px;
    padding-right:20px;
    text-align:center;
    font-weight:bold;
}
```
