### ISSUE TITLE
Nested header is not showing on scrolling vertically.

### ISSUE THREAD

**Issue by Ilayaraja-n** [jspreadsheet/ce#781]
Nested header is not showing on scrolling vertically.

Note: This issue is not available in the jExcel version 2.1.0

![Nested_Header_1](https://user-images.githubusercontent.com/46338652/71245651-3952ed00-233b-11ea-844f-7c43cc1c2b50.png)
![Nested_Header_2](https://user-images.githubusercontent.com/46338652/71245663-3ce67400-233b-11ea-862d-eb4339ae5868.png)

**Comment by heidashuaiheniwawa** [comment]
you can try to add css:
.jexcel > thead {
  top: 0 !important;
  position: -webkit-sticky !important;
  position: sticky !important;
  z-index: 3 !important;
}

**Comment by fkreis** [comment]
Experiencing the same issue in Jspreadsheet v4.10.1
Workaround for me as an adjusted version of @heidashuaiheniwawa suggestion:

```css
.jexcel > thead {
            top: 0 !important;
            position: sticky !important;
        }
```
