### ISSUE TITLE
Split thead css

### ISSUE THREAD

**Issue by sasha-x** [jspreadsheet/ce#981]
How do you about moving 
```css
.jexcel > thead > tr > td
{
    position: -webkit-sticky;
    position: sticky;
}
```
to some separate css class and may be make a new config option for that.

Reason is if table placed into `position:fixed;` container, when sticky thead behaves a bit strange (places over tbody) on page scrolling down in Chrome browser.
